.TH "ALPINO-DACT" "1" "June 05, 2011"
.SH NAME
alpino-dact \- Alpino treebank viewer
.SH SYNOPSIS
.B alpino-dact 
.I corpus
.SH DESCRIPTION
.B alpino-dact 
is a viewer for Alpino treebanks. See the online help manual for further
information.
.SH AUTHOR
Dact was written by Daniël de Kok, Jelmer van der Linde, and Lars Buitinck.
