FIND_PACKAGE(PkgConfig)
PKG_CHECK_MODULES(PC_ICONV iconv)
SET(ICONV_DEFINITIONS ${PC_ICONV_CFLAGS_OTHER})

FIND_PATH(ICONV_INCLUDE_DIR NAMES iconv.h
    HINTS
   ${PC_ICONV_INCLUDEDIR}
   ${PC_ICONV_INCLUDE_DIRS}
  )

FIND_LIBRARY(ICONV_LIBRARIES NAMES iconv
    HINTS
   ${PC_ICONV_LIBDIR}
   ${PC_ICONV_LIBRARY_DIRS}
  )

# handle the QUIETLY and REQUIRED arguments and set LIBXML2_FOUND to TRUE if 
# all listed variables are TRUE
INCLUDE(FindPackageHandleStandardArgs)
FIND_PACKAGE_HANDLE_STANDARD_ARGS(Iconv DEFAULT_MSG ICONV_LIBRARIES ICONV_INCLUDE_DIR)

MARK_AS_ADVANCED(ICONV_INCLUDE_DIR ICONV_LIBRARIES)

