FIND_PATH(ALPINOCORPUS_INCLUDE_DIR NAMES AlpinoCorpus/IndexedCorpusReader.hh)

FIND_LIBRARY(ALPINOCORPUS_LIBRARIES NAMES alpino_corpus )

# handle the QUIETLY and REQUIRED arguments and set LIBXML2_FOUND to TRUE if 
# all listed variables are TRUE
INCLUDE(FindPackageHandleStandardArgs)
FIND_PACKAGE_HANDLE_STANDARD_ARGS(AlpinoCorpus DEFAULT_MSG ALPINOCORPUS_LIBRARIES ALPINOCORPUS_INCLUDE_DIR)

MARK_AS_ADVANCED(ALPINOCORPUS_INCLUDE_DIR ALPINOCORPUS_LIBRARIES)

