set(INDEXEDCORPUS_ROOT_DIR ${INDEXEDCORPUS_ROOT_DIR} CACHE PATH "IndexedCorpus base directory location (optional, used for nonstandard installation paths)" FORCE)

if(INDEXEDCORPUS_ROOT_DIR STREQUAL "")
  set(INDEXEDCORPUS_ROOT_DIR "/opt/IndexedCorpus")
endif(INDEXEDCORPUS_ROOT_DIR STREQUAL "")

IF (INDEXEDCORPUS_INCLUDE_DIR AND INDEXEDCORPUS_LIBRARIES)
   # in cache already
   SET(IndexedCorpus_FIND_QUIETLY TRUE)
ENDIF (INDEXEDCORPUS_INCLUDE_DIR AND INDEXEDCORPUS_LIBRARIES)

FIND_PATH(INDEXEDCORPUS_INCLUDE_DIR IndexedCorpus/ActCorpusReader.hh
	PATHS ${INDEXEDCORPUS_ROOT_DIR}
)

FIND_LIBRARY(INDEXEDCORPUS_LIBRARIES NAMES corpus
	PATHS ${INDEXEDCORPUS_ROOT_DIR}
)

INCLUDE(FindPackageHandleStandardArgs)
FIND_PACKAGE_HANDLE_STANDARD_ARGS(IndexedCorpus DEFAULT_MSG INDEXEDCORPUS_LIBRARIES INDEXEDCORPUS_INCLUDE_DIR)

MARK_AS_ADVANCED(INDEXEDCORPUS_INCLUDE_DIR INDEXEDCORPUS_LIBRARIES INDEXEDCORPUS_LIBRARY_DIR)

