#FIND_PACKAGE(PkgConfig)
#PKG_CHECK_MODULES(PC_INDEXEDCORPUS IndexedCorpus)
#SET(INDEXEDCORPUS_DEFINITIONS ${PC_INDEXEDCORPUS_CFLAGS_OTHER})

FIND_PATH(INDEXEDCORPUS_INCLUDE_DIR NAMES IndexedCorpus/IndexedCorpusReader.hh)

FIND_LIBRARY(INDEXEDCORPUS_LIBRARIES NAMES corpus )

# handle the QUIETLY and REQUIRED arguments and set LIBXML2_FOUND to TRUE if 
# all listed variables are TRUE
INCLUDE(FindPackageHandleStandardArgs)
FIND_PACKAGE_HANDLE_STANDARD_ARGS(IndexedCorpus DEFAULT_MSG INDEXEDCORPUS_LIBRARIES INDEXEDCORPUS_INCLUDE_DIR)

MARK_AS_ADVANCED(INDEXEDCORPUS_INCLUDE_DIR INDEXEDCORPUS_LIBRARIES)

