FIND_PATH(QDICTZIP_INCLUDE_DIR NAMES QDictZip/QDictZipFile.hh)

FIND_LIBRARY(QDICTZIP_LIBRARIES NAMES qdictzip)

# handle the QUIETLY and REQUIRED arguments and set LIBXML2_FOUND to TRUE if 
# all listed variables are TRUE
INCLUDE(FindPackageHandleStandardArgs)
FIND_PACKAGE_HANDLE_STANDARD_ARGS(QDictZip DEFAULT_MSG QDICTZIP_LIBRARIES QDICTZIP_INCLUDE_DIR)

MARK_AS_ADVANCED(QDICTZIP_INCLUDE_DIR QDICTZIP_LIBRARIES)

